# Generated by Django 4.1.2 on 2022-10-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_agent_personalmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='lastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='patronymic',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
