# Generated by Django 4.1.2 on 2022-10-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_alter_agent_lastname_alter_agent_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='idDeal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
